accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name="login"),
    path('logout/',views.logout, name="logout"),
    path('user_page/<int:id>/', views.user_page, name="user_page"),
    path('edit_profile/<int:id>/', views.edit_profile, name='edit_profile'),
    path('follow/<int:id>/', views.follow, name='follow')
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #환경변수에 접근
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls'))

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.



class User(AbstractUser):
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers", blank = True)
    introduce = models.TextField()
    profile_image = ProcessedImageField(
                upload_to='accounts/images', #저장 위치
                processors=[ResizeToFill(150,150)], #크기지정
                format='JPEG',
                options={'quality':90},
                blank = True,
        )

    def __str__(self):
        return self.username

posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings
# Create your models here.



class Hashtag(models.Model):
    content = models.CharField(max_length=100)
    def  __str__(self):
        return self.content


class Post(models.Model):
    content = models.CharField(max_length=100)
    # image = models.ImageField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post_set",blank=True)
    hashtag = models.ManyToManyField(Hashtag, blank = True)

class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
                upload_to='posts/images', #저장 위치
                processors=[ResizeToFill(600,600)], #크기지정
                format='JPEG',
                options={'quality':90},
        )
        
        
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
    
    
# class Like(models.Model):
#     post = models.ForeignKey(Post, on_delete=True) 
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User



class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ['username', 'email', ]
        
        
class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['email', 'introduce', 'profile_image']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm # 인증&권한:AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.method == "POST": # 저장
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts:list")
        
    else : # 입력할 수 있는 폼
        form = CustomUserCreationForm()
    return render(request,"accounts/form.html",{"form":form})
    
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("posts:list")
    else :
        form = AuthenticationForm()
    
    return render(request,"accounts/form.html", {"form":form})

def logout(request):
    auth_logout(request)
    return redirect("posts:list")
    
    
def user_page(request, id):
    User = get_user_model()
    user_info = User.objects.get(id=id)
    return render(request, 'accounts/user_page.html',{'user_info':user_info})
    
@login_required
def follow(request, id):
    User = get_user_model()
    me = request.user
    you = User.objects.get(id=id)
    if me != you:
        if you in me.followings.all():
            #취소 버튼
            me.followings.remove(you)
            
        else:
            #추가버튼
            me.followings.add(you)
    
    return redirect('accounts:user_page', id)
    
    
@login_required
def edit_profile(request, id):
    User = get_user_model()
    user = User.objects.get(id=id)
    me = request.user
    if me == user:
        if request.method == 'POST':
            form = CustomUserChangeForm(request.POST, request.FILES, instance = user)
            if form.is_valid():
                form.save()
                return redirect('accounts:user_page', id)
        else:
            form = CustomUserChangeForm(instance = user)
        return render(request, 'accounts/form.html', {'form':form})
    else:
        return redirect('posts:list')
        
    

accounts/templates/accounts/form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block body %}
    {% if request.resolver_match.url_name == "signup" %}
        <h1>회원가입</h1>
    {% elif request.resolver_match.url_name == 'login' %}
        <h2>로그인</h2>
    {% else %}
        <h2>프로필수정</h2>
    {% endif %}
    <form action = "" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" name=""/>
    </form>
    {% if request.resolver_match.url_name == "login" %}
        <a href="{% provider_login_url 'kakao' method = 'auth2' %}">카카오로그인</a>
    {% endif %}    
{% endblock %}

accounts/templates/accounts/user_page.html
{% extends 'base.html' %}

{% block body %}
    <!--사용자 정보 출력 시작-->
    <div class="row my-5">
        <div class="col-4 d-flex-justify-content-center">
            <!--프로필이미지-->
            {% if user_info.profile_image %}
            <img src="{{user_info.profile_image.url}}" alt='' class='rounded-circle'></img>
            {% else %}
            <img src="/media/accounts/images/defalut.jpg" alt='' class='rounded-circle'></img>
            {% endif %}
        </div>
        <div class="col-6">
            <!--유저 정보-->
            <div class="row d-flex align-items-center">
                <h1>{{user_info.username}}</h1>
                {% if user != user_info %}
                    {% if user_info in user.followings.all %}
                        <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-light">팔로잉</a>
                    {% else %}
                        <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-primary">팔로우</a>
                    {% endif %}
                    
                {% else %}
                    <a href="{% url 'accounts:edit_profile' user_info.id %}" class="btn btn-light">프로필수정</a>
                {% endif %}
            </div>
            <div class="row d-flex justify-content-start">
                <h5 class="mx-3">게시물 : {{user_info.post_set.count}}</h5>
                <h5 class="mx-3">팔로잉 : {{user_info.followings.count}}</h5>
                <h5 class="mx-3">팔로워 : {{user_info.followers.count}}</h5>
            </div>
            <div class="row">
                <div class="col-6 offset-4">
                    <p>{{user_info.introduce}}</p>
                </div>
            </div>
        </div>
    </div>
    <!--사용자 정보 출력 끝-->
    
    <!--작성글 출력 시작-->
    <div class="card-columns">
        {% for post in user_info.post_set.all %}
            {% include 'posts/_post.html' %}
        {% endfor %}
    </div>
    <!--작성글 출력 끝-->
{% endblock %}