accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name="login"),
    path('logout/',views.logout, name="logout"),
    path('user_page/<int:id>/', views.user_page, name="user_page"),
    path('edit_profile/<int:id>/', views.edit_profile, name='edit_profile'),
    path('follow/<int:id>/', views.follow, name='follow')
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #환경변수에 접근
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls'))

]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.list,name='list'),
    path('create/',views.create, name="create"),
    path('<int:id>/update/',views.update,name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:post_id>/comment/create', views.comment_create, name='comment_create'),
    path('<int:post_id>/comment/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),

    path('<int:post_id>/like',views.like,name='like'),
    path('hashtag/<int:id>/', views.hashtag, name = 'hashtag')
]

posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings
# Create your models here.



class Hashtag(models.Model):
    content = models.CharField(max_length=100)
    def  __str__(self):
        return self.content


class Post(models.Model):
    content = models.CharField(max_length=100)
    # image = models.ImageField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post_set",blank=True)
    hashtag = models.ManyToManyField(Hashtag, blank = True)

class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
                upload_to='posts/images', #저장 위치
                processors=[ResizeToFill(600,600)], #크기지정
                format='JPEG',
                options={'quality':90},
        )
        
        
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
    
    
# class Like(models.Model):
#     post = models.ForeignKey(Post, on_delete=True) 
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    

posts/forms.py
from django import forms
from .models import Post, Image, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content',]
        
class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        # fields = '__all__'
        fields = ['file',]
        widgets = {
            'file' : forms.FileInput(attrs={'multiple': True})
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]
        
    

posts/views.py
from django.shortcuts import render,redirect
from .forms import PostForm, ImageForm, CommentForm
from .models import Post, Comment, Hashtag
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
# Create your views here.

def list(request):
    posts = Post.objects.all()
    comment_form = CommentForm()
    return render(request,'posts/list.html',{'posts':posts, 'comment_form':comment_form})
    
def create(request):
    # 1. get 방식으로 데이터를 입력할 form을 요청한다.
    # 4. 사용자가 데이터를 입력해서 post방식으로 요청한다.
    # 9. 사용자가 다시 적절한 데이터를 입력해서 post방식으로 요청한다.
    if request.method == "POST":
        # 5. post방식으로 저장요청을 받고, 데이터를 받아 PostForm에 넣어서 인스턴스화 한다.
        # 10. 5번과 같음
        post_form = PostForm(request.POST) # 사진을 받기 위해 request.FILES도 추가
        image_form = ImageForm(request.POST,request.FILES)
        # 6. 데이터 검증을 한다.
        # 11. 6번과 같음 
        if post_form.is_valid():
            # 12. 적절한 데이터가 들어온다. 데이터를 저장하고 list페이지로 리다이렉트
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            
            #해쉬태그 기능 추가
            content = post_form.cleaned_data.get('content')
            content_words = content.split()
            for word in content_words:
                if word[0] == "#":
                    tag = Hashtag.objects.get_or_create(content=word)
                    post.hashtag.add(tag[0])
                    
            #해쉬태그 끝
            for image in request.FILES.getlist('file') :
                request.FILES['file'] = image
                image_form = ImageForm(request.POST,request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.post = post 
                    image.save()
            return redirect("posts:list")
        else :
            # 7. 적절하지 않은 데이터가 들어온다.
            pass
    else :
        # 2. PostForm을 인스턴스화 시켜서 form에 저장한다.
        post_form = PostForm()
        image_form = ImageForm()
    # 3. form을 담아서 create.html을 보내준다.
    # 8. 사용자가 입력한 데이터는 form에 담아진 상태로 다시 form을 담아서 create.html을 보내준다.
    return render(request,'posts/form.html',{'post_form':post_form,'image_form':image_form})
    
    
    
    


@login_required 
def update(request,id):
    post = Post.objects.get(id=id)
    if post.user == request.user :
        if request.method == "POST":
            post_form = PostForm(request.POST, instance=post)
            if post_form.is_valid():
                post_form.save()
                
                #해쉬태그 기능 추가
                post.hashtag.clear()
                content = post_form.cleaned_data.get('content')
                content_words = content.split()
                for word in content_words:
                    if word[0] == "#":
                        tag = Hashtag.objects.get_or_create(content=word)
                        post.hashtag.add(tag[0])
                #해쉬태그 끝
                
                return redirect("posts:list")
        else:
            post_form = PostForm(instance=post)
        return render(request, 'posts/form.html',{'post_form':post_form})
    else :
        return redirect("posts:list")

def delete(request,id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect("posts:list")
    
    
@login_required 
@require_POST
def comment_create(request, post_id):
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = Post.objects.get(id=post_id)
            comment.save()
            return redirect('posts:list')
            
@login_required
def comment_delete(request, post_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if comment.user == request.user:
        comment.delete()
    return redirect('posts:list')
            
@login_required
def like(require, post_id):
    user = require.user
    post = Post.objects.get(id=post_id)
    #사용자가 좋아요를 눌렀다면
    if user in post.likes.all():
        post.likes.remove(user)
    #사용자가 좋아요를 누르지 않았다면
    else:
        post.likes.add(user)

    return redirect('posts:list')
    
def hashtag(request, id):
    hashtag = Hashtag.objects.get(id = id)
    posts = hashtag.post_set.all()
    comment_form = CommentForm
    
    
    return render(request, 'posts/list.html', {'posts':posts, 'comment_form':comment_form, 'hashtag':hashtag})

posts/templates/posts/_post.html
<div class="card my-5">
  <div class="card-header">
    <a href="{% url 'accounts:user_page' post.user.id %}" style="color:black"><h5 class="card-text">{{post.user}}</h5></a>
  </div>
  {% if post.image_set %}
    <div id="post{{post.id}}" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        {% for image in post.image_set.all %}
          <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
            <img src="{{image.file.url}}" class="d-block w-100" alt="...">
          </div>
        {% endfor %}
      </div>
      <a class="carousel-control-prev" href="#post{{post.id}}" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#post{{post.id}}" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  {% else %}
    <img src="..." class="card-img-top" alt="...">
  {% endif %}
  
  <div class="card-body">
    <!-- 좋아요 버튼 시작 -->
    {% if user in post.likes.all %}
      <a href="{% url 'posts:like' post.id %}"><i class="fas fa-heart" style="color:#ed4956"></i></a>
    {% else %}
      <a href="{% url 'posts:like' post.id %}"><i class="far fa-heart" style="color:black"></i></a>
    {% endif %}
    <!-- 좋아요 버튼 끝-->
    <p class="card-text"><strong>{{post.user}}</strong> {{post.content}}</p>
    <p class="card-text">좋아요 {{post.likes.count}}개</p>
    {% if post.user == user %}
      <a href="{% url 'posts:update' post.id %}" class="btn btn-warning">수정</a>
      <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">삭제</a>
    {% endif %}
  </div>
  
  <!--댓글을 보여주는 부분-->
  <div class="card-body">
    {% for comment in post.comment_set.all %}
      <p class="card-text"><strong>{{comment.user}}</strong> {{comment.content}}</p>
      {% if comment.user == user %}
        <a href="{% url 'posts:comment_delete' post.id comment.id %}" class="btn btn-danger">삭제</a>
      {% endif %}
    {% empty%}
      <p class="card-text">댓글이 없어요 ㅠㅠㅠ</p>
    {% endfor %}
  </div>
  
  <div class="card-body">
    <form action="{% url 'posts:comment_create' post.id %}" method='post'>
      {% csrf_token %}
      {{comment_form.content}}
      <input type="submit"/>
    </form>
  </div>
</div>

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form action="" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock %}

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form method = 'post' enctype="multipart/form-data" accept = 'image/*'> 
    <!--파일이 들어갈수 있음 (enctype="multipart/form-data")-->
        {% csrf_token %}
        {% bootstrap_form post_form %}
        {% if image_form %}
            {% bootstrap_form image_form %}
        {% endif %}
        <input type="submit" name=""/>
    </form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block body %}
    <div class="row">
        <div class="col-6">
            {% for post in posts %}
                {% include 'posts/_post.html' %}
            {% endfor%}
        </div>
    </div>
{% endblock %}